#!/usr/bin/env python3
"""Regenerate every pre-recorded firmware speech asset with omni-os's own ST voice.

Nothing proprietary is embedded: the loader's clips (os/boot/uefi/src/speech/*.pcm), its
word banks (word_bank_<lang>.bin + src/word_bank_gen.rs) and the kernel menu clips
(os/kernel/x86_64/src/speech/*.pcm) are all synthesized by ST (voice-st, 0BSD), from the
texts in tools/voice/firmware-clips.json.

ST renders 48 kHz 24-bit mono WAV; the firmware streams 24 kHz 16-bit mono raw PCM. The
conversion is a fixed windowed-sinc low-pass (no aliasing) and an exact 2:1 decimation.

    python tools/voice/gen-firmware-speech.py PATH/TO/st[.exe]
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "tools" / "voice" / "firmware-clips.json"
SPEECH = ROOT / "os" / "boot" / "uefi" / "src" / "speech"
WORD_INDEX = ROOT / "os" / "boot" / "uefi" / "src" / "word_bank_gen.rs"

# 48 kHz -> 24 kHz: 127-tap Blackman-windowed sinc, cutoff 10.8 kHz (0.9 x new Nyquist).
_TAPS = 127
_n = np.arange(_TAPS) - (_TAPS - 1) / 2
_CUTOFF = 10_800 / 48_000
LOWPASS = 2 * _CUTOFF * np.sinc(2 * _CUTOFF * _n) * np.blackman(_TAPS)
LOWPASS /= LOWPASS.sum()


def synthesize(st: str, lang: str, text: str) -> np.ndarray:
    """ST -> float samples at 48 kHz."""
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "clip.wav"
        subprocess.run(
            [st, "--backend", "compact", "-l", lang, "-t", text, "-o", str(out)],
            check=True, capture_output=True,
        )
        with wave.open(str(out)) as w:
            assert (w.getframerate(), w.getnchannels(), w.getsampwidth()) == (48_000, 1, 3), \
                "ST must render 48 kHz 24-bit mono"
            raw = w.readframes(w.getnframes())
    b = np.frombuffer(raw, dtype=np.uint8).reshape(-1, 3).astype(np.int32)
    s = b[:, 0] | (b[:, 1] << 8) | (b[:, 2] << 16)
    s = np.where(s & 0x800000, s - 0x1000000, s)
    return s.astype(np.float64) / 8_388_608.0


def to_pcm24k(x: np.ndarray) -> np.ndarray:
    """Low-pass, keep every second sample, round to signed 16-bit."""
    y = np.convolve(x, LOWPASS, mode="same")[::2]
    return np.clip(np.round(y * 32_767.0), -32_768, 32_767).astype("<i2")


def trim(pcm: np.ndarray) -> np.ndarray:
    """Same rule as the original word bank: drop |sample| < 220 at both ends, keep 15 ms."""
    loud = np.flatnonzero(np.abs(pcm.astype(np.int32)) >= 220)
    if loud.size == 0:
        return pcm[:0]
    pad = 360
    return pcm[max(0, loud[0] - pad): min(pcm.size, loud[-1] + pad + 1)]


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    st = sys.argv[1]
    clips = json.loads(MANIFEST.read_text(encoding="utf-8"))
    for c in clips:
        pcm = to_pcm24k(synthesize(st, c["lang"], c["text"]))
        (ROOT / c["out"] / f"{c['name']}.pcm").write_bytes(pcm.tobytes())
    print(f"clips: {len(clips)}")

    # Word banks: same vocabulary and order as the current index, re-voiced by ST.
    index = WORD_INDEX.read_text(encoding="utf-8")
    sections = {"fr": "FR_INDEX", "en": "EN_INDEX"}
    for lang, table in sections.items():
        body = index[index.index(f"pub static {table}"):]
        body = body[: body.index("];") + 2]
        words = re.findall(r'\("([^"]+)", \d+, \d+\)', body)
        blob, rows = bytearray(), []
        for word in words:
            pcm = trim(to_pcm24k(synthesize(st, lang, word))).tobytes()
            rows.append(f'    ("{word}", {len(blob)}, {len(pcm)}),')
            blob += pcm
        (SPEECH / f"word_bank_{lang}.bin").write_bytes(bytes(blob))
        head = body[: body.index("= &[") + 4]
        index = index.replace(body, head + "\n" + "\n".join(rows) + "\n];")
        print(f"word bank {lang}: {len(words)} words, {len(blob)} bytes")
    index = re.sub(
        r"\A(//!.*\n)+",
        "//! Generated by tools/voice/gen-firmware-speech.py - do not edit by hand.\n"
        "//!\n"
        "//! The word bank index: for each language, `(word, offset, length)` into the packed\n"
        "//! `word_bank_<lang>.bin` blob of 24 kHz mono PCM, voiced by omni-os's own ST voice.\n",
        index,
    )
    for language in ("French", "English"):
        index = index.replace(f"spoken by the installed {language} voice", "spoken by the ST voice")
    WORD_INDEX.write_text(index, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
