[package]
name = "accessible-windows-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
aw-acpi = { path = "../crates/aw-acpi" }
aw-fs-core = { path = "../crates/aw-fs-core" }
aw-storefs = { path = "../crates/aw-storefs" }
libfuzzer-sys = "0.4"

[[bin]]
name = "rsdp"
path = "fuzz_targets/rsdp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "awfs_checkpoint"
path = "fuzz_targets/awfs_checkpoint.rs"
test = false
doc = false
bench = false

[[bin]]
name = "awstore_manifest"
path = "fuzz_targets/awstore_manifest.rs"
test = false
doc = false
bench = false
