"""Generate os/boot/uefi/src/protocols_gen.rs: every protocol GUID declared by the TianoCore EDK II
reference (MdePkg/MdePkg.dec, the UEFI and PI protocol definitions), at the pinned commit the
firmware tools use. The loader probes each one at boot (os/boot/uefi/src/platform.rs).

  python tools/uefi/gen-protocols.py MdePkg.dec os/boot/uefi/src/protocols_gen.rs

MdePkg.dec: https://raw.githubusercontent.com/tianocore/edk2/<commit>/MdePkg/MdePkg.dec
"""
import re
import struct
import sys

EDK2_COMMIT = "2970e5699ba6267f3384ffab20f96647578aebc8"  # edk2-stable202608
LINE = re.compile(
    r"^\s*(gEfi[A-Za-z0-9]*ProtocolGuid)\s*=\s*\{\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,"
    r"\s*(0x[0-9a-fA-F]+)\s*,\s*\{([^}]*)\}\s*\}"
)


def main() -> int:
    source, out = sys.argv[1], sys.argv[2]
    rows = {}
    for line in open(source, encoding="utf-8", errors="replace"):
        m = LINE.match(line)
        if not m:
            continue
        name, d1, d2, d3, d4 = m.groups()
        tail = [int(x, 16) for x in d4.split(",") if x.strip()]
        if len(tail) != 8:
            raise SystemExit(f"bad GUID for {name}")
        raw = struct.pack("<IHH", int(d1, 16), int(d2, 16), int(d3, 16)) + bytes(tail)
        rows[name] = raw
    if len(rows) < 200:
        raise SystemExit(f"only {len(rows)} protocols parsed")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// @generated by tools/uefi/gen-protocols.py from TianoCore EDK II MdePkg/MdePkg.dec\n")
        f.write(f"// at commit {EDK2_COMMIT} (edk2-stable202608). Do not edit.\n\n")
        f.write("/// (EDK II name, EFI_GUID in memory layout) for every protocol MdePkg declares.\n")
        f.write("#[rustfmt::skip]\n")
        f.write(f"pub const PROTOCOLS: [(&str, [u8; 16]); {len(rows)}] = [\n")
        for name in sorted(rows):
            short = name[len("gEfi"):-len("ProtocolGuid")]
            body = ", ".join(f"0x{b:02x}" for b in rows[name])
            f.write(f'    ("{short}", [{body}]),\n')
        f.write("];\n")
    print(f"PROTOCOLS={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
